### ISSUE TITLE
Final Stress Test Bug

### ISSUE THREAD

**Issue by Peetytwist** [ps-wow/Broker_Classic_Training#13]
Hey,
I get this message while using it at the final stress test:

Message: Interface\AddOns\Broker_Classic_Training\main.lua:217: attempt to compare nil with number
Time: Fri Aug  9 16:01:31 2019
Count: 1
Stack: Interface\AddOns\Broker_Classic_Training\main.lua:217: attempt to compare nil with number
Interface\AddOns\Broker_Classic_Training\main.lua:217: in function `FilterSpellBooks'
Interface\AddOns\Broker_Classic_Training\main.lua:125: in function `BuildTrainingData'
Interface\AddOns\Broker_Classic_Training\main.lua:298: in function `?'
...ing\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ing\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ing\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
..._Classic_Training\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <..._Classic_Training\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by davidcraig** [comment]
Hi, thanks for the report, is this when levelling up did you notice, or under certain circumstances? I noticed there was an issue when levelling up which I have just uploaded a fix for, if this does not update resolve this issue let me know :)

**Comment by davidcraig** [comment]
Closing this as I assume it is fixed due to no further activity on it :)
