### ISSUE TITLE
Error when hovering for tooltip

### ISSUE THREAD

**Issue by Rusher1337** [ps-wow/Broker_Classic_Training#14]
Date: 2019-08-11 17:05:09
ID: 57
Error occured in: Global
Count: 5
Message: ..\AddOns\Broker_Classic_Training\main.lua line 200:
   attempt to concatenate field 'quest_name' (a nil value)
Debug:
   [C]: ?
   Broker_Classic_Training\main.lua:200: FormatSpells()
   Broker_Classic_Training\main.lua:110: BuildTrainingData()
   Broker_Classic_Training\main.lua:286: OnTooltipShow()
   Broker_Classic_Training\main.lua:293:
      Broker_Classic_Training\main.lua:289
   TitanClassic\LDBToTitanClassic.lua:327:
      TitanClassic\LDBToTitanClassic.lua:286
AddOns:
  AraBrokerGuildFriends, vr80
  AraBrokerXP, vr6
  AtlasLootClassic, vv1.1.2-beta
  BasicMinimap, vv1-classic
  BrokeruClock, vv3.3.11
  BrokerSysMon, vv1.0.3
  BrokerClassicTraining, vv1.0.0
  Details, vv8.2.0.7167 (core 140)
  Dominos, v8.2.12
  DominosCast
  DominosRoll
  Elephant, v3.7.8
  ModernQuestWatch, v1.0.5
  Omen, v3.2.2
  OmniCC, v8.1.1
  Prat30, vr1203      
  Prat30Libraries
  QuestFrameFixer, v1.1.1
  ShadowedUnitFrames, vv4.2.2
  Swatter, v5.0.0
  TidyPlatesThreatPlates, v9.1.12
  TitanClassicAmmo, v1.0.1.11302
  TitanClassicBag, v1.0.1.11302
  TitanClassicClock, v1.0.1.11302
  TitanClassicGold, v1.0.1.11302
  TitanClassicLocation, v1.0.1.11302
  TitanClassicLootType, v1.0.1.11302
  TitanClassicPerformance, v1.0.1.11302
  TitanClassicRepair, v1.0.1.11302
  TitanClassicVolume, v1.0.1.11302
  TitanClassicXP, v1.0.1.11302
  TitanClassic, v1.0.1.11302
  VendorPrice, v1.1.1
  WeakAuras, v2.14.0-beta4
  AraBrokerMoney, vr12
  AraBrokerReputations, vr12
  DBMCore, v1.13.0
  DBMDefaultSkin
  DBMStatusBarTimers

**Comment by davidcraig** [comment]
Hi, do you know what class and level you got this error on?

**Comment by davidcraig** [comment]
I think I have found the issue, I have uploaded a new version, will close bug for now but feel free to reopen if still not fixed once curse updates the addon.

**Comment by Rusher1337** [comment]
Hi, it was an lvl 11 Warrior, i will Test the new Version tomorrow, big
thanks!

David Craig <notifications@github.com> schrieb am So., 11. Aug. 2019, 21:58:

**Comment by Rusher1337** [comment]
Problem is solved, Quest Source is unknown now.

**Comment by davidcraig** [comment]
Yup, had to put unknown in for now until I get the name of the quest :)
