### ISSUE TITLE
Warrior Rend Bug

### ISSUE THREAD

**Issue by Rusher1337** [ps-wow/Broker_Classic_Training#15]
Rend Rank 1 at lvl 4 ist displayed in the Broker Tooltip. My Warrior lvl 11 already got Rend rank 2.
Other Spells at Rank two are tracked correctly.

**Comment by Rusher1337** [comment]
This bug happens with spells which have only the heighest rank in the spellbook.
Caster can downrank, Warriors can not. The addon ist thinking you are missing an lower spell.
![classic_training_prob](https://user-images.githubusercontent.com/53384143/64209495-fc084380-cea0-11e9-9c46-5f01ae0ab76d.png)

**Comment by davidcraig** [comment]
Thank you for the report and screenshot, I was not aware that Warriors don't have multiple ranks of spells.

I will need to add an additional check for this, but I don't have a high level warrior, so it will take me a couple of days to look into this, I will probably upload some changes tomorrow and see if you are around to help test :)

**Comment by Rusher1337** [comment]
Testing will be no problem 👍
Big thanks for your work

David Craig <notifications@github.com> schrieb am Mi., 4. Sep. 2019, 09:34:

**Comment by davidcraig** [comment]
I am looking into this now, I am wondering, is it all ranked spells for warrior, or just certain ones?

**Comment by davidcraig** [comment]
I have just pushed up a change to test this out, I have only took up to rank 3 charge, let me know if rank 1 disappears :)

**Comment by Rusher1337** [comment]
looks like its working :)

**Comment by davidcraig** [comment]
Ok I will work over the coming day or two to do the same thing for the other spells :)

**Comment by Rusher1337** [comment]
i hope i fixed them well for you - for me its working.

**Comment by davidcraig** [comment]
Closing this issue for now, can re-open if we find any bugs :)
