### ISSUE TITLE
nil 'quest_name' line 200

### ISSUE THREAD

**Issue by Kataclasm** [ps-wow/Broker_Classic_Training#16]
I am currently a level 23 Shaman and I am on the quest chain to get my water totem.  Starting getting the error below.  The quest is called Call of Water.  Once i commented out the if/then statement around line 200, the error went away with the addon showing:

Spells
20 Healing Stream Totem Rank 1          Quest

[but of course, with no quest name]

The Error:

4x Broker_Classic_Training\main.lua:200: attempt to concatenate field 'quest_name' (a nil value)
Broker_Classic_Training\main.lua:200: in function `FormatSpells'
Broker_Classic_Training\main.lua:110: in function `BuildTrainingData'
Broker_Classic_Training\main.lua:285: in function `OnTooltipShow'
ChocolateBar\Chocolate.lua:249: in function <ChocolateBar\Chocolate.lua:228>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 kbDEBUG = true
 Enable = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 Feed = <table> {
 }
 FilterSpells = <function> defined @Broker_Classic_Training\main.lua:130
 FormatSpellBooks = <function> defined @Broker_Classic_Training\main.lua:237
 SetDefaultModulePrototype = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateLabel = <function> defined @Broker_Classic_Training\main.lua:66
 GetLabels = <function> defined @Broker_Classic_Training\main.lua:71
 Dump = <function> defined @Broker_Classic_Training\main.lua:30
 name = "Broker_Classic_Training"
 IsEnabled = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 SPELLS_CHANGED = <function> defined @Broker_Classic_Training\main.lua:311
 RegisterMessage = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 constants = <table> {
 }
 IsModule = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 SendMessage = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 baseName = "Broker_Classic_Training"
 PLAYER_LEVEL_UP = <function> defined @Broker_Classic_Training\main.lua:306
 SetEnabledState = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 PLAYER_ENTERING_WORLD = <function> defined @Broker_Classic_Training\main.lua:301
 enabledState = true
 SetDefaultModuleState = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 RegisterEvent = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 FormatSpells = <function> defined @Broker_Classic_Training\main.lua:163
 BuildTrainingData = <function> defined @Broker_Classic_Training\main.lua:91
 GetClassColourHex = <function> defined @Broker_Classic_Training\main.lua:37
 IterateModules = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterAllEvents = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 FilterSpellBooks = <function> defined @Broker_Classic_Training\main.lua:212
 GetName = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 UnregisterEvent = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
self = GameTooltip {
 0 = <userdata>
 SetSpellBookItem = <function

**Comment by davidcraig** [comment]
Hi, I have just pushed a commit for this quest that should fix this issue, let me know.

**Comment by Kataclasm** [comment]
Unfortunately, i have already completed that quest and have trained the skill.  I'll let you know if i see this problem with any other quest-connected training item, or when i get to the questline for the air totem.
