### ISSUE TITLE
Shaman Cure Disease is lvl 22, not lvl 14

### ISSUE THREAD

**Issue by Kataclasm** [ps-wow/Broker_Classic_Training#17]
Addon claimed Cure Disease was available for training at level 14, but when i went to the trainer, i saw it wasn't available until level 22.

**Comment by davidcraig** [comment]
Thank you for the report, I have confirmed Curse Disease is a level 22 spell, also the price was off, so I have updated that as well.

**Comment by Kataclasm** [comment]
Thanks for the fix.  Yes, i forgot to mention the price as well, but i had noticed that too.
