### ISSUE TITLE
Error "UNIT_THREAT_LIST_UPDATE" AceEvent

### ISSUE THREAD

**Issue by Rusher1337** [ps-wow/Broker_Classic_Training#18]
i get the following error every time after Login:

Date: 2019-09-13 18:23:22
ID: 1
Error occured in: Global
Count: 1
Message: ..._Classic_Training\Libs\AceEvent-3.0\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "UNIT_THREAT_LIST_UPDATE"
Debug:
   [C]: RegisterEvent()
   ..._Classic_Training\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: OnUsed()
   ...ra_Broker_Guild_Friends\libs\CallbackHandler-1.0.lua:142: RegisterEvent()
   Omen\Omen.lua:592:
      Omen\Omen.lua:589
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:380: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:695:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AraBrokerGuildFriends, vr80
  AraBrokerMoney, vr12
  AraBrokerReputations, vr12
  AraBrokerXP, vr6
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BasicMinimap, vv1-classic
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BrokerClassicTraining, vv1.0.0
  BrokerSysMon, vv1.0.3
  BrokeruClock, vv3.3.11
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  Dominos, v8.2.25
  DominosCast, v
  DominosRoll, v
  Elephant, v3.7.8
  GatherMate2, v1.45
  iMail, v8.2.0
  ModernQuestWatch, v1.0.8
  Omen, v3.2.2
  OmniCC, v8.2.4
  Prat30, v3.7.34
  Prat30Libraries, v
  QuestFrameFixer, v1.1.1
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.2.3
  TitanClassic, v1.0.6.11302
  TitanClassicAmmo, v1.0.6.11302
  TitanClassicBag, v1.0.6.11302
  TitanClassicClock, v1.0.6.11302
  TitanClassicGold, v1.0.6.11302
  TitanClassicLocation, v1.0.6.11302
  TitanClassicLootType, v1.0.6.11302
  TitanClassicPerformance, v1.0.6.11302
  TitanClassicRepair, v1.0.6.11302
  TitanClassicVolume, v1.0.6.11302
  TitanClassicXP, v1.0.6.11302
  VendorPrice, v1.2.4
  WeakAuras, v2.14.6
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=6a5)

**Comment by davidcraig** [comment]
Weird, was this happening before or you only just noticed it now, it makes sense because threat doesn't have an api, when I first released the addon I used one of the earlier versions of Ace library, the next version that came out introduced other bugs so just left the version as it was, I can experiment with newer versions :)

**Comment by davidcraig** [comment]
Just updated Ace3 in 72cdce59 so lets see if this fixes it :)

**Comment by Rusher1337** [comment]
i just updated, no fix :(

Date: 2019-09-14 19:05:31
ID: 1
Error occured in: Global
Count: 1
Message: ..._Classic_Training\Libs\AceEvent-3.0\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "UNIT_THREAT_LIST_UPDATE"
Debug:
   [C]: RegisterEvent()
   ..._Classic_Training\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: OnUsed()
   ...ra_Broker_Guild_Friends\libs\CallbackHandler-1.0.lua:142: RegisterEvent()
   Omen\Omen.lua:592:
      Omen\Omen.lua:589
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:380: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:695:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AraBrokerGuildFriends, vr80
  AraBrokerMoney, vr12
  AraBrokerReputations, vr12
  AraBrokerXP, vr6
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.11
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BasicMinimap, vv1-classic
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BrokerClassicTraining, vv1.0.0
  BrokerSysMon, vv1.0.3
  BrokeruClock, vv3.3.11
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  Dominos, v8.2.26
  DominosCast, v
  DominosRoll, v
  Elephant, v3.7.8
  GatherMate2, v1.45
  iMail, v8.2.0
  ModernQuestWatch, v1.0.8
  Omen, v3.2.2
  OmniCC, v8.2.4
  Prat30, v3.7.36
  Prat30Libraries, v
  QuestFrameFixer, v1.1.1
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.2.3
  TitanClassic, v1.0.7.11302
  TitanClassicAmmo, v1.0.7.11302
  TitanClassicBag, v1.0.7.11302
  TitanClassicClock, v1.0.7.11302
  TitanClassicGold, v1.0.7.11302
  TitanClassicLocation, v1.0.7.11302
  TitanClassicLootType, v1.0.7.11302
  TitanClassicPerformance, v1.0.7.11302
  TitanClassicRepair, v1.0.7.11302
  TitanClassicVolume, v1.0.7.11302
  TitanClassicXP, v1.0.7.11302
  VendorPrice, v1.2.4
  WeakAuras, v2.14.6
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=6a1)
